apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyAgImF1dGhzIjogeyAgICAiZ2hjci5pbyI6IHsgICAgICAiYXV0aCI6ICJlWFJ1T21kb2NGOXZNbkpJUkcwNVZ6aFJjVmgxV2pSVlEwTTJWMmRFYkZZMGFHUTVkMmt4YjJVNVJXME5DZz09IiB9ICB9fQ0K
type: kubernetes.io/dockerconfigjson
